#!/bin/bash

#SBATCH --gres=gpu:a100:1
#SBATCH -p compute
#SBATCH -J hdln
#SBATCH -t 1-23:59:59


source /home/cosuji/anaconda3/etc/profile.d/conda.sh
conda activate agent


model_path = "/home/support/llm/Llama-3.3-70B-Instruct"
model_id = "/home/support/llm/Llama-3.1-70B-Instruct"
dataset = "/home/cosuji/spinning-storage/cosuji/NLG_Exp/news_headline/PENS/personalization/pers_preprocessed.csv"
write_path = "/home/cosuji/spinning-storage/cosuji/NLG_Exp/news_headline/results"


echo "Headline Generation Started!!!"

python3 ../prompt.py --model_path "$model_path" \
			--model_id "$model_id" \
                    	--data_path "$dataset" \
                    	--write_path "$write_path"

echo "Generation finished!!!"
